### ISSUE TITLE
Any result examples?

### ISSUE THREAD

**Issue by LynnHo** [hjweide/fader-networks#1]
@hjweide Thanks for your code! Have you reproduced the results of the paper？ Can you provide any results of your code?

**Comment by hjweide** [comment]
@LynnHo, no, I have not yet been able to reproduce the results from the paper.  There are two possible reasons for this, namely that (1) my implementation is incorrect, or (2) the model selection step, which I have not added, is really important.  Below I show two examples from the test set, sampled after 180 epochs of training:

This one is swapping the "Eyeglasses" attribute:
![183504](https://user-images.githubusercontent.com/6610704/32056972-fdee09e2-ba33-11e7-9fad-bfbec171592c.png)

And swapping the "No_Beard" attribute:
![183246](https://user-images.githubusercontent.com/6610704/32057025-1d0846c6-ba34-11e7-9368-b74d39980978.png)

As you can see, the autoencoder (reconstruction) part of the model kind of works, even if the results are a little blurry (perhaps the architecture is wrong, or perhaps I just need to train it for a longer time).  The part of the model that learns the attributes, however, clearly isn't working.  This is one of the things I'm unsure of --- is the model selection necessary for the model to work at all, or does it just improve the results?

Unfortunately, I won't have time to work on this for the next few months.  If you find any bugs, please submit a pull request.  Also feel free to let me know if you have any questions or if you're unsure about anything in my implementation, I'd love to get it working at some point in the future.

**Comment by LynnHo** [comment]
@hjweide The official code is released. https://github.com/facebookresearch/FaderNetworks
